### ISSUE TITLE
Is there a way to uninstall/revert back the settings?

### ISSUE THREAD

**Issue by ibehnam** [TanakritBenz/keyboard#1]
I already have Karabiner and Hammerspoon and have set some custom keys on them. Will they be gone if I install this? If anything goes wrong, how should I uninstall this and go back to previous settings?

**Comment by TanakritBenz** [comment]
Hey @ibehnam, sorry for the late reply! I didn't expect anyone to 👀 this repo, as it's just a fork of [jasonrudolph's work](https://github.com/jasonrudolph/keyboard), and I simply just tweaked the settings to better suit my liking. 😅 


Yes, you can back up your old Karabiner and Hammerspoon settings. However, It depends on how you installed the programs originally.

If you're coming from the vanilla installations of Karabiner and Hammerspoon.
- For Karabiner, the default location of the settings can be found here: https://karabiner-elements.pqrs.org/docs/json/location/.
- For Hammerspoon, the default location of the settings should be in `~/.hammerspoon/` folder.

If you're coming from jasonrudolph's repo or another fork of it.
- The settings are in the `hammerspoon` and `karabiner` folders. Just temporarily copy them out to somewhere to back it up and you should be safe.
